/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { MultiCall } from "./MultiCall";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { MultiCall__factory } from "./factories/MultiCall__factory";
